version: '2'
services:
  isucoin:
    build: ruby
    environment:
      BUNDLE_PATH: "/bundle"
      RACK_ENV: production
    command:
      - "sh"
      - "-c"
      - "bundle install && bundle exec puma -p 5000 -t 5:5"
    working_dir: /app
    volumes:
      - bundle:/bundle
      - ./ruby:/app
      - ./public:/public

volumes:
  bundle:
